apiVersion: v1
kind: Service
metadata:
  name: debug
  namespace: network-system
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: debug
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9898
  externalIPs:
    - 192.168.35.10
    - fd37:dc42:5e0a:0035::10
