apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
makeIPTablesUtilChains: false
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.255.1
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
  name: core.erdii.net
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  kubeletExtraArgs:
    node-ip: 192.168.255.1,fd37:dc42:5e0a:ffff::1
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.0
imageRepository: k8s.gcr.io
clusterName: kubernetes
certificatesDir: /etc/kubernetes/pki
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
  - localhost
  - 127.0.0.1
  - 192.168.255.1
  - fd37:dc42:5e0a:640e:0:fffe::1
  - core.erdii.online
controllerManager: {}
featureGates:
  IPv6DualStack: true
dns:
  type: CoreDNS
etcd: {}
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16,fd37:dc42:5e0a:640e::/64
  serviceSubnet: 10.96.0.0/12,fd37:dc42:5e0a:640f::/108
scheduler: {}
