apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-lab-static
  namespace: network-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "br-lab-static",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br-lab",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
