apiVersion: dns.routerd.net/v1alpha1
kind: DNSServer
metadata:
  name: lab
  namespace: network-system
spec:
  replicas: 2
  forward:
    from: "."
    to: ["9.9.9.9"]
    except: ["home.erdii.net"]
    policy: Random
  cache:
    ttl: 86400s
