apiVersion: v1
kind: Service
metadata:
  name: lab-dns
  namespace: network-system
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: routerd-dns
    app.kubernetes.io/managed-by: routerd
    app.kubernetes.io/instance: core
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  externalIPs:
    - 192.168.35.2
    - fd37:dc42:5e0a:0035::2
