apiVersion: dns.routerd.net/v1alpha1
kind: DNSServer
metadata:
  name: lab
  namespace: network-system
spec:
  # with 2 replicas, every other request timed out
  # nevermind - this also happens with 1 replica
  replicas: 1
  forward:
    from: "."
    to: ["9.9.9.9"]
    except: ["lab.erdii.net"]
    policy: Random
  cache:
    ttl: 86400s
