apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-cluster-lb
  name: storage-cluster-lb
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-cluster-lb
  template:
    metadata:
      labels:
        app: storage-cluster-lb
    spec:
      containers:
      - name: coredns
        command:
        - /gobetween
        args:
        - -c
        - /etc/gobetween/gobetween.toml
        image: docker.io/yyyar/gobetween:0.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/gobetween
          name: config-volume
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: gobetween.toml
            path: gobetween.toml
          name: storage-cluster-lb
        name: config-volume
