apiVersion: ipam.routerd.net/v1alpha1
kind: IPv4Lease
metadata:
  name: storage-cluster-lb
  namespace: lab
spec:
  type: Static
  pool:
    name: lab
  static:
    address: 192.168.35.50
---
apiVersion: ipam.routerd.net/v1alpha1
kind: IPv6Lease
metadata:
  name: storage-cluster-lb
  namespace: lab
spec:
  type: Static
  pool:
    name: lab
  static:
    address: fd37:dc42:5e0a:0035::50
