apiVersion: v1
kind: Service
metadata:
  name: storage-cluster-lb
  namespace: lab
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  selector:
    app: storage-cluster-lb
  ports:
    - name: https
      protocol: TCP
      port: 6443
      targetPort: 6443
  externalIPs:
    - 192.168.35.50
    - fd37:dc42:5e0a:0035::50
